version: '1'

services:
  app:
    image: 'assignment:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
      - rabbit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banking_db??characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbit

  db:
    image: 'postgres:15.3-alpine'
    container_name: db
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=banking_db
    volumes:
      - ./src/test/resources/ddl/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  rabbit:
    image: 'rabbitmq:management-alpine'
    container_name: rabbit
    ports:
    - 5672:5672
    - 15672:15672
